### ISSUE TITLE
SlackService is not available

### ISSUE THREAD

**Issue by alper** [bamada/nest-slack-bolt#459]
I get:

```
Error: Nest can't resolve dependencies of the TestController (?). Please make sure that the argument SlackService at index [0] is available in the ControllersModule context.

Potential solutions:
- Is ControllersModule a valid NestJS module?
- If SlackService is a provider, is it part of the current ControllersModule?
- If SlackService is exported from a separate @Module, is that module imported within ControllersModule?
  @Module({
    imports: [ /* the Module containing SlackService */ ]
  })

```

Not sure what to do. Documentation does not give anything here.

**Comment by bamada** [comment]
Hi there! Thanks for reporting this issue. This error typically occurs when NestJS can't find the `SlackService` provider in the module's context. Let me help you resolve this.

### The Error Explained
The error suggests that your `TestController` is trying to inject `SlackService`, but NestJS can't find it in the dependency injection container. This usually happens due to incomplete module configuration.

### Solution

1. First, make sure you've imported the `SlackModule` properly. Here's how I've configured it in my testing environment:

```typescript
@Module({
  imports: [
    SlackModule.forRoot({
      // your slack configuration here
    }),
    // other imports...
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class YourModule {}
```

2. If your `TestController` is in a different module (e.g., `ControllersModule`), you need to:
   - Either import `SlackModule` in that module:

```typescript
@Module({
  imports: [SlackModule], // Note: no forRoot() here
  controllers: [TestController],
})
export class ControllersModule {}
```

   - Or ensure the module containing your `TestController` has access to the `SlackModule`:

```typescript
// controllers.module.ts
@Module({
  imports: [SlackModule],
  controllers: [TestController],
})
export class ControllersModule {}

// test.controller.ts
@Controller()
export class TestController {
  constructor(private readonly slackService: SlackService) {}
  // ... your controller logic
}
```

### Common Gotchas to Check:
1. Verify that `SlackModule` is properly exported from its source module
2. Ensure you're using `forRoot()` only once in your application (typically in your root module)
3. Check that `SlackService` is properly provided in the `SlackModule`

Could you share your current module structure and how you've configured the `SlackModule`? This would help me provide more specific guidance.

Let me know if you need any clarification or run into other issues!
